/*
Copyright 2022 Max T.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthenticatedOriginPullsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AuthenticatedOriginPullsParameters struct {

	// +crossplane:generate:reference:type=AuthenticatedOriginPullsCertificate
	// +crossplane:generate:reference:refFieldName=AuthenticatedOriginPullsCertificateRef
	// +crossplane:generate:reference:selectorFieldName=AuthenticatedOriginPullsCertificateSelector
	// +kubebuilder:validation:Optional
	AuthenticatedOriginPullsCertificate *string `json:"authenticatedOriginPullsCertificate,omitempty" tf:"authenticated_origin_pulls_certificate,omitempty"`

	// Reference to a AuthenticatedOriginPullsCertificate to populate authenticatedOriginPullsCertificate.
	// +kubebuilder:validation:Optional
	AuthenticatedOriginPullsCertificateRef *v1.Reference `json:"authenticatedOriginPullsCertificateRef,omitempty" tf:"-"`

	// Selector for a AuthenticatedOriginPullsCertificate to populate authenticatedOriginPullsCertificate.
	// +kubebuilder:validation:Optional
	AuthenticatedOriginPullsCertificateSelector *v1.Selector `json:"authenticatedOriginPullsCertificateSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Required
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// +crossplane:generate:reference:type=Zone
	// +crossplane:generate:reference:refFieldName=ZoneRef
	// +crossplane:generate:reference:selectorFieldName=ZoneSelector
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneRef *v1.Reference `json:"zoneRef,omitempty" tf:"-"`

	// Selector for a Zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneSelector *v1.Selector `json:"zoneSelector,omitempty" tf:"-"`
}

// AuthenticatedOriginPullsSpec defines the desired state of AuthenticatedOriginPulls
type AuthenticatedOriginPullsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthenticatedOriginPullsParameters `json:"forProvider"`
}

// AuthenticatedOriginPullsStatus defines the observed state of AuthenticatedOriginPulls.
type AuthenticatedOriginPullsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthenticatedOriginPullsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatedOriginPulls is the Schema for the AuthenticatedOriginPullss API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type AuthenticatedOriginPulls struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AuthenticatedOriginPullsSpec   `json:"spec"`
	Status            AuthenticatedOriginPullsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatedOriginPullsList contains a list of AuthenticatedOriginPullss
type AuthenticatedOriginPullsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthenticatedOriginPulls `json:"items"`
}

// Repository type metadata.
var (
	AuthenticatedOriginPulls_Kind             = "AuthenticatedOriginPulls"
	AuthenticatedOriginPulls_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthenticatedOriginPulls_Kind}.String()
	AuthenticatedOriginPulls_KindAPIVersion   = AuthenticatedOriginPulls_Kind + "." + CRDGroupVersion.String()
	AuthenticatedOriginPulls_GroupVersionKind = CRDGroupVersion.WithKind(AuthenticatedOriginPulls_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthenticatedOriginPulls{}, &AuthenticatedOriginPullsList{})
}
