name: Publish
on:
  workflow_dispatch: # for testing (TODO remove)
  push:
    tags:
    - '*'

env:
  # Common versions
  GO_VERSION: '1.19'
  GOLANGCI_VERSION: 'v1.50.0'
  DOCKER_BUILDX_VERSION: 'v0.8.2'

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}}

      - name: Build
        uses: actions/github-script@v6
        with:
          script: |
            const { DOCKER_METADATA_OUTPUT_LABELS } = process.env
            const labels = JSON.parse(DOCKER_METADATA_OUTPUT_LABELS)

            console.log(labels)

            const args = Object.entries(labels).map(([key, value]) => `--label ${JSON.stringify(key)} ${JSON.stringify(value)}`)

            console.log(args.join(" "))
